### ISSUE TITLE
Broken link in organizer manual 

### ISSUE THREAD

**Issue by juliaelman** [DjangoGirls/organizer-manual#8]
After taking a quick peruse through the manual, I noticed that several links were broken throughout the text (primarily on the `step-by-step` page).

**Comment by bittner** [comment]
Sorry to tell you, but links on the step-by-step page are still broken. Tested on http://organize.djangogirls.org/step_by_step/index.html
I think I figured out what the problem is: All the links seem to reference a README.html file, but the target document should be index.html (or omitted completely).

**Comment by juliaelman** [comment]
@bittner no need to be sorry! Glad you caught it and fixed! :D

@asendecka want to take a look at this fix and test before merging?
